# Generated by Django 2.2.4 on 2020-05-28 20:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_ordered', models.IntegerField()),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='product',
            name='item',
        ),
        migrations.RemoveField(
            model_name='product',
            name='itemprice',
        ),
        migrations.AddField(
            model_name='product',
            name='description',
            field=models.CharField(default='description', max_length=45),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, default='10', max_digits=5),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='uploader',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post_uploaded', to='first_app.Register'),
        ),
    ]
