# Generated by Django 2.2.4 on 2020-05-28 20:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0002_auto_20200528_2010'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Order',
        ),
        migrations.RemoveField(
            model_name='product',
            name='description',
        ),
        migrations.RemoveField(
            model_name='product',
            name='price',
        ),
        migrations.AddField(
            model_name='product',
            name='item',
            field=models.CharField(default='default', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='itemprice',
            field=models.DecimalField(decimal_places=2, default='10', max_digits=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='uploader',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quotes_uploaded', to='first_app.Register'),
        ),
    ]
